# Tutorial \#1: Hands-on Introduction to Quantum Computing
In this first part of the tutorial you will learn the fundamentals of quantum computing including superposition of states, destructive measurement, entanglement, quantum gates and circuits. You will be able to understand and calculate the output of a quantum circuit.

## Getting started

To get a better understanding of how quantum computing works from the mathematical point of view we implement a couple of quantum gates by hand and investigate how they act on quantum states. This is all done using the Python package `numpy` whose functionality we make available under the alias `np` with the following command

In [1]:
import numpy as np
import math 

Let us represent the single-qubit state

$$ \lvert\psi\rangle = \alpha \lvert 0 \rangle + \beta \lvert 1 \rangle, \qquad |\alpha|^2+|\beta|^2 = 1 $$

by its two complex-valued coefficients $ \alpha $ and $ \beta $ of the state vector as a vector.

As we just shown, the quantum state $  \lvert 0 \rangle $ is represented by the vector $\left( \begin{array}{c} 1 \\ 0 \end{array} \right)$, whereas the quantum state $ \lvert 1 \rangle $ corresponds to the vector $\left( \begin{array}{c} 0 \\ 1 \end{array} \right)$, which can be defined as:

In [2]:
q0 = np.array([[1],[0]])
print('q0=',q0)

q0= [[1]
 [0]]


In [3]:
q1 = np.array([[0],[1]])
print('q1=',q1)

q1= [[0]
 [1]]


Quantum gates are represented by matrices. The unitary operator (matrix) of the X gate is $\left( \begin{array}{cc} 0 & 1 \\ 1 & 0 \end{array}\right) $ that can be defined as:


In [4]:
X = np.array([[0,1],[1,0]])
print(X)

[[0 1]
 [1 0]]


**Exercise 1**

The resulting state of applying a X gate to a given quantum state $ \lvert\psi_{in}\rangle$ can be calculated as: 

$$ \lvert\psi_{out}\rangle = X\lvert\psi_{in}\rangle $$

We can then calculate the result of applying a X gate to quantum state $\lvert 0 \rangle $ as follows:


In [5]:
out1 = np.dot(X,q0)
print(out1)

[[0]
 [1]]


Similarly, the result of applying a X gate to quantum state $\lvert 1 \rangle $ can be calculated as:


In [6]:
out2 = np.dot(X,q1)
print(out2)

[[1]
 [0]]


Let's now calculate the result of applying a Hadamard gate (H) to state $  \lvert 0 \rangle $ and to state $  \lvert 1 \rangle $. The matrix representing the H gate is $ \frac{1}{\sqrt{2}}\left(\begin{array}{cc} 1 & 1 \\ 1 & -1 \end{array}\right) $

In [7]:
## your code goes here
H = 1/math.sqrt(2)*np.array([[1,1],[1,-1]])

out3 = np.dot(H,q0)
print(out3)

out4 = np.dot(H,q1)
print(out4)

[[0.70710678]
 [0.70710678]]
[[ 0.70710678]
 [-0.70710678]]


**Exercise 2**

The output state after applying three single-qubit gates to a quantum state can be calculated as:

$$ \lvert\psi_{out}\rangle = U_3U_2U_1\lvert\psi_{in}\rangle $$

being $U_3$ the last gate (most right gate).

Let's now calculate the output state when applying the following series of gates to state $\lvert 0 \rangle $ 

![Figure exercise 2](images/Fig_Ex2.png)


First, we need to define the matrix correspoding to the Z gate: $\left( \begin{array}{cc} 1 & 0 \\ 0 & -1 \end{array}\right) $

In [8]:
## your code goes here
Z = np.array([[1,0],[0,-1]])

Now, we can calculate the output using the formula shown above.

**Note that the dot function only allows two matrices as arguments**

In [9]:
## your code goes here (HZH)

applyH = np.dot(H,q0)
applyZ = np.dot(Z,applyH)
final = np.dot(H,applyZ)
print(final)

[[2.23711432e-17]
 [1.00000000e+00]]


In [10]:
## your code goes here (HXH)

applyH = np.dot(H,q0)
applyX = np.dot(X,applyH)
final2 = np.dot(H,applyX)
print(final2)

[[1.00000000e+00]
 [2.23711432e-17]]


**Exercise 3**

When combining n qubits, the resulting quantum state can be calculated as: 

$$ \lvert\psi\rangle = \lvert\psi_1\rangle  \otimes \lvert\psi_2\rangle \otimes \lvert\psi_3\rangle \otimes ... \lvert\psi_n\rangle$$

For instance, the quantum state of a system composed by two qubits $q_0 = \lvert0\rangle$ and $q_1=\lvert0\rangle$ is calculated as $\lvert0\rangle \otimes \lvert0\rangle $ that in its vector form is  $\left( \begin{array}{c} 1 \\ 0 \\ 0\\ 0\end{array} \right)$

Let's now derive the vectors corresponding to states $\lvert 00 \rangle$, $\lvert 01 \rangle$, $\lvert 10 \rangle$, and $\lvert 11 \rangle$.    

**Kronecker product pyhton command: np.kron(A,B)**


In [11]:
## your code goes here

q00 = np.kron(q0,q0)
q01 = np.kron(q0,q1)
q10 = np.kron(q1,q0)
q11 = np.kron(q1,q1)

print("q00=", q00)
print("q01=", q01)
print("q10=", q10)
print("q11=", q11)


q00= [[1]
 [0]
 [0]
 [0]]
q01= [[0]
 [1]
 [0]
 [0]]
q10= [[0]
 [0]
 [1]
 [0]]
q11= [[0]
 [0]
 [0]
 [1]]


**Exercise 4**

The output state of a two-qubit circuit when applying a single-qubit gate to each of the qubits can be calculated as:

$$ \lvert\psi_{out}\rangle = U_1 \otimes U_2 \lvert\psi_{in}\rangle $$

being $U_1$ the gate operating the top qubit and $U_2$ the one applied to the bottom qubit.

Let's now calculate the output state when applying the following gates to state $\lvert 00 \rangle $ 

![Figure exercise 3](images/Fig_Ex3.png)


First, we need to define the matrix corresponding to the Identity gate $\left( \begin{array}{cc} 1 & 0 \\ 0 & 1 \end{array}\right) $

In [12]:
## your code goes here (matrix I gate)
I = np.array([[1,0],[0,1]])

Second, we calculate the Kronecker product of the two gates $ H \otimes I \$

**Kronecker product pyhton command: np.kron(A,B)**

In [13]:
## your code goes here

HI = np.kron(H,I)

Finally, we calculate resulting state as $\lvert\psi_{out}\rangle = H \otimes I \lvert 00\rangle $


In [14]:
## your code goes here (HZH)

HIq00 = np.dot(HI,q00)
print(HIq00)

[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]


That corresponds to the state $ \frac{1}{\sqrt{2}}(\lvert 00 \rangle + \lvert 10 \rangle) $


**Exercise 5**

The following circuit is used to create the so-called Bell pairs:

![Figure exercise 4](images/Fig_Ex4.png)

Show that by chaning the input states and performing the corresponding vector-matrix multiplications, the four Bell pairs $ \beta_{00}= \frac{1}{\sqrt{2}}(\lvert 00 \rangle + \lvert 11 \rangle) $,  $ \beta_{01}= \frac{1}{\sqrt{2}}(\lvert 01 \rangle + \lvert 10 \rangle) $,  $ \beta_{10}= \frac{1}{\sqrt{2}}(\lvert 00 \rangle - \lvert 11 \rangle) $, and  $ \beta_{11}= \frac{1}{\sqrt{2}}(\lvert 01 \rangle - \lvert 10 \rangle) $  can indeed be obtained.

In [16]:
## your code goes here

#CNOT matrix
CNOT = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

#Kronecker product H and I

HI = np.kron(H,I)

#Product with the CNOT
HICNOT = np.dot(CNOT, HI)

#Product with the input state

b00 = np.dot(HICNOT,q00)
b01 = np.dot(HICNOT,q01)
b10 = np.dot(HICNOT,q10)
b11 = np.dot(HICNOT,q11)

print(b00)
print(b01)
print(b10)
print(b11)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]
